<a href="https://colab.research.google.com/github/AryanVansh/AI-Assignment/blob/main/Diabetes_patient_classification_using_naive_bayes_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!unzip "/content/drive/MyDrive/MASTER/Projects_and_datasets/Complete-classification-algos-of-Supervised-Learning--main.zip"

Archive:  /content/drive/MyDrive/MASTER/Projects_and_datasets/Complete-classification-algos-of-Supervised-Learning--main.zip
2a5d30b66d2eec2409760701dd1259bf7065c0c5
   creating: Complete-classification-algos-of-Supervised-Learning--main/
  inflating: Complete-classification-algos-of-Supervised-Learning--main/Classification_Supervised_ML.ipynb  
   creating: Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/
  inflating: Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/Admission Chance.csv  
  inflating: Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/Anagrams.csv  
  inflating: Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/Anscombe.csv  
  inflating: Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/Attention.csv  
  inflating: Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/Big Sales Data.csv  
  inflating: Complete-classification-algos-of-Super

Importig necessary libraries

In [2]:
import pandas as pd
import numpy as np

Creating Dataset from Dataframe

In [4]:
df = pd.read_csv(r"/content/Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/Diabetes.csv")
df.head

<bound method NDFrame.head of      pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0              6      148         72       35        0  33.6  0.627   50   
1              1       85         66       29        0  26.6  0.351   31   
2              8      183         64        0        0  23.3  0.672   32   
3              1       89         66       23       94  28.1  0.167   21   
4              0      137         40       35      168  43.1  2.288   33   
..           ...      ...        ...      ...      ...   ...    ...  ...   
763           10      101         76       48      180  32.9  0.171   63   
764            2      122         70       27        0  36.8  0.340   27   
765            5      121         72       23      112  26.2  0.245   30   
766            1      126         60        0        0  30.1  0.349   47   
767            1       93         70       31        0  30.4  0.315   23   

     diabetes  
0           1  
1           0  
2        

Analysing the data

In [5]:
df.describe

<bound method NDFrame.describe of      pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0              6      148         72       35        0  33.6  0.627   50   
1              1       85         66       29        0  26.6  0.351   31   
2              8      183         64        0        0  23.3  0.672   32   
3              1       89         66       23       94  28.1  0.167   21   
4              0      137         40       35      168  43.1  2.288   33   
..           ...      ...        ...      ...      ...   ...    ...  ...   
763           10      101         76       48      180  32.9  0.171   63   
764            2      122         70       27        0  36.8  0.340   27   
765            5      121         72       23      112  26.2  0.245   30   
766            1      126         60        0        0  30.1  0.349   47   
767            1       93         70       31        0  30.4  0.315   23   

     diabetes  
0           1  
1           0  
2    

All the columns in the dataset

In [6]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

Transfering all the data in 'x' dataframe

In [7]:
x=df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes']]

Droping the diabetes column

In [8]:
x=df.drop("diabetes",axis=1)
x.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0            6      148         72       35        0  33.6  0.627   50
1            1       85         66       29        0  26.6  0.351   31
2            8      183         64        0        0  23.3  0.672   32
3            1       89         66       23       94  28.1  0.167   21
4            0      137         40       35      168  43.1  2.288   33

Saving the diabetese column in y dataset

In [10]:
y=df[["diabetes"]]
y.head()

diabetes
0         1
1         0
2         1
3         0
4         1

Splitting the dataset

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70,random_state=3000)
x_train

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
366            6      124         72        0        0  27.6  0.368   29
655            2      155         52       27      540  38.7  0.240   25
753            0      181         88       44      510  43.3  0.222   26
693            7      129         68       49      125  38.5  0.439   43
536            0      105         90        0        0  29.6  0.197   46
..           ...      ...        ...      ...      ...   ...    ...  ...
78             0      131          0        0        0  43.2  0.270   26
601            6       96          0        0        0  23.7  0.190   28
26             7      147         76        0        0  39.4  0.257   43
563            6       99         60       19       54  26.9  0.497   32
508            2       84         50       23       76  30.4  0.968   21

[537 rows x 8 columns]

Changing the training data int vector form

In [12]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.fit_transform(x_test)
x_train
x_test

array([[-1.11934777, -1.09045954,  0.66676504, ...,  0.80270241,
        -0.66102112, -0.84012405],
       [-0.81514855, -3.609721  , -1.03073014, ..., -0.92951506,
        -0.90733043, -0.93451542],
       [ 0.70584753,  0.07919756,  0.16750175, ...,  0.21246535,
         0.66322246,  0.19818101],
       ...,
       [-0.81514855, -3.609721  ,  0.26735441, ..., -0.54457785,
        -0.48622097, -1.02890679],
       [-0.81514855, -0.9405035 , -0.13205622, ..., -0.49325288,
        -0.83582127, -1.02890679],
       [ 1.61844518,  1.90866124,  0.81654403, ..., -0.24945931,
         1.9344963 ,  1.61405155]])

Training the model

In [13]:
from sklearn.naive_bayes import GaussianNB
_=GaussianNB()
_.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [14]:
y_pred=_.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1])

Confusion matrix

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[126,  25],
       [ 36,  44]])

Classification of report

In [16]:
from sklearn.metrics import classification_report
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.78      0.83      0.81       151\n           1       0.64      0.55      0.59        80\n\n    accuracy                           0.74       231\n   macro avg       0.71      0.69      0.70       231\nweighted avg       0.73      0.74      0.73       231\n'